image: node:latest

cache: # 缓存
  paths:
    - node_modules/

stages: # 分段
  - install
  - build
  - deploy

安装依赖:
  image: node:lts
  tags:
    - vitesse-lite
  stage: install
  script:
    - npm install -g pnpm
    - pnpm i

打包:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week

docker:
  image: docker
  stage: deploy
  script:
    - whoami
    - docker ps
    - docker build -t front-devops-demo-image .
    - if [ $(docker ps -aq --filter name=front-devops-demo-container) ]; then docker rm -f front-devops-demo-container;fi
    - docker run -d -p 9000:80 --name front-devops-demo-container front-devops-demo-image
  needs:
    - job: 打包
      artifacts: true
